server:
  port: 8989
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8030/file-upload-mt
    username: postgres
    password: Postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
